<?php /** @var \Snowdog\Menu\Block\NodeType\Product $block */ ?>
<?php
$nodeId = $block->getId();
$class = $block->getMenuClass();
$dataAttribute = '';
$classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
$title = $block->getTitle();

if ($nodeId) {
    $dataAttribute = ' data-menu="menu-' . $nodeId . '"';
}

?>
<div class="<?php echo $classLink ?>"<?php echo $dataAttribute ?> >
    <?php echo $title ?>
</div>
